[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink_/=lib/chainlink/contracts/src/v0.8/",
    "@chainlink-local/=lib/chainlink-local/",
    "@forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
]
